// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PaiementTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void confirmation() {
    driver.get("https://www.demoblaze.com/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("cartur")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("safa");
    vars.put("client_name", driver.findElement(By.id("name")).getAttribute("value"));
    driver.findElement(By.id("country")).click();
    driver.findElement(By.id("country")).sendKeys("tunis");
    vars.put("client_country", driver.findElement(By.id("country")).getAttribute("value"));
    driver.findElement(By.id("city")).sendKeys("tunisia");
    vars.put("client_city", driver.findElement(By.id("city")).getAttribute("value"));
    driver.findElement(By.id("card")).sendKeys("22551122");
    driver.findElement(By.id("month")).sendKeys("02");
    driver.findElement(By.id("year")).sendKeys("2001");
    driver.findElement(By.cssSelector("#orderModal .btn-primary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#orderModal .btn-primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("h2:nth-child(6)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".confirm")).click();
    driver.close();
  }
}
