// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PanierTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ajoutProduit() {
    driver.get("https://www.demoblaze.com/");
    driver.manage().window().setSize(new Dimension(990, 824));
    driver.findElement(By.cssSelector(".col-lg-4:nth-child(1) .card-img-top")).click();
    driver.findElement(By.linkText("Add to cart")).click();
    assertThat(driver.switchTo().alert().getText(), is("Product added"));
    vars.put("product_name", driver.findElement(By.cssSelector(".name")).getText());
    System.out.println(vars.get("product_name").toString());
    driver.close();
  }
  @Test
  public void gestionPanier() {
    driver.get("https://www.demoblaze.com/");
    driver.manage().window().setSize(new Dimension(990, 824));
    driver.findElement(By.linkText("Previous")).click();
    driver.findElement(By.id("cartur")).click();
    driver.findElement(By.cssSelector(".success:nth-child(1) > td:nth-child(2)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("td:nth-child(2)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Delete")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("td:nth-child(2)"));
      assert(elements.size() == 0);
    }
    driver.close();
  }
}
