// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("https://insat.rnu.tn/");
    driver.manage().window().setSize(new Dimension(990, 824));
    driver.findElement(By.linkText("Toutes les actualités")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".max-w-md:nth-child(1) .text-2xl")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".hover\\3Atext-primary-300:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,138.39999389648438)");
    driver.findElement(By.cssSelector("a:nth-child(1) .min-w-\\[25px\\]")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector("a:nth-child(3) > .flex")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,140.8000030517578)");
  }
}
